// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQQg-fh5PQTp6mS0pGmXAMoAN1E3ZE57c',
    appId: '1:177722010370:web:f33e2d2befd5c60875b01b',
    messagingSenderId: '177722010370',
    projectId: 'bubbleshield',
    authDomain: 'bubbleshield.firebaseapp.com',
    storageBucket: 'bubbleshield.appspot.com',
    measurementId: 'G-YR876RK3SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlvezXCPejJnSIJiLUZCSG9t4DuLGEaEI',
    appId: '1:177722010370:android:35662ceae7beed1175b01b',
    messagingSenderId: '177722010370',
    projectId: 'bubbleshield',
    storageBucket: 'bubbleshield.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEDn-Sg3FOsGbS_GA19XPf7sOURWq52mU',
    appId: '1:177722010370:ios:da366c5b1db2784875b01b',
    messagingSenderId: '177722010370',
    projectId: 'bubbleshield',
    storageBucket: 'bubbleshield.appspot.com',
    iosBundleId: 'com.example.faf',
  );
}
